module.exports = {
  expo: {
    name: "Eisenhower - Priority Matrix",
    slug: "eisenhower",
    version: "1.0.0",
    orientation: "portrait",
    icon: "./assets/icon.png",
    userInterfaceStyle: "automatic",
    newArchEnabled: true,
    splash: {
      image: "./assets/splash-icon.png",
      resizeMode: "contain",
      backgroundColor: "#0F172A",
    },
    ios: {
      supportsTablet: false,
      bundleIdentifier: "com.darchevert.eisenhower",
      entitlements: {
        "com.apple.security.application-groups": ["group.com.darchevert.eisenhower"],
      },
      infoPlist: {
        NSCalendarsUsageDescription: "L'app accède à votre calendrier pour afficher vos événements dans les widgets.",
        NSCalendarsFullAccessUsageDescription: "L'app accède à votre calendrier pour afficher vos événements dans les widgets.",
      },
    },
    android: {
      package: "com.darchevert.eisenhower",
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        backgroundColor: "#0F172A",
      },
      edgeToEdgeEnabled: true,
      permissions: ["READ_CALENDAR"],
    },
    web: {
      favicon: "./assets/favicon.png",
      bundler: "metro",
      output: "single",
    },
    extra: {
      eas: {
        projectId: "d5f2dc0d-a751-4064-bb71-e6b6b675a4f4",
      },
    },
    owner: "darchevert",
    plugins: [
      ["@bacons/apple-targets"],
      [
        "react-native-android-widget",
        {
          widgets: [
            {
              name: "Eisenhower",
              label: "Eisenhower — Do First",
              minWidth: "180dp",
              minHeight: "110dp",
              targetCellWidth: 3,
              targetCellHeight: 2,
              description: "Urgent & important tasks",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerQ2",
              label: "Eisenhower — Schedule",
              minWidth: "180dp",
              minHeight: "110dp",
              targetCellWidth: 3,
              targetCellHeight: 2,
              description: "Important but not urgent tasks",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerQ3",
              label: "Eisenhower — Delegate",
              minWidth: "180dp",
              minHeight: "110dp",
              targetCellWidth: 3,
              targetCellHeight: 2,
              description: "Urgent but not important tasks",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerQ4",
              label: "Eisenhower — Eliminate",
              minWidth: "180dp",
              minHeight: "110dp",
              targetCellWidth: 3,
              targetCellHeight: 2,
              description: "Neither urgent nor important tasks",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerMatrix",
              label: "Eisenhower Matrix",
              minWidth: "250dp",
              minHeight: "200dp",
              targetCellWidth: 4,
              targetCellHeight: 3,
              description: "All four quadrants at a glance",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerDashboard",
              label: "Eisenhower — Task Dashboard",
              minWidth: "180dp",
              minHeight: "110dp",
              targetCellWidth: 3,
              targetCellHeight: 2,
              description: "All tasks with quadrant counts",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerDouble",
              label: "Eisenhower — Double Section",
              minWidth: "250dp",
              minHeight: "110dp",
              targetCellWidth: 4,
              targetCellHeight: 2,
              description: "Do First and Schedule side by side",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerDateTasks",
              label: "Eisenhower — Date & Tasks",
              minWidth: "250dp",
              minHeight: "110dp",
              targetCellWidth: 4,
              targetCellHeight: 2,
              description: "Today's date with tasks by quadrant",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerCalendarTasks",
              label: "Eisenhower — Calendrier & Tâches",
              minWidth: "250dp",
              minHeight: "200dp",
              targetCellWidth: 4,
              targetCellHeight: 3,
              description: "Mini calendrier mensuel avec tâches par quadrant",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerToday",
              label: "Eisenhower — Date du jour",
              minWidth: "110dp",
              minHeight: "110dp",
              targetCellWidth: 2,
              targetCellHeight: 2,
              description: "Date du jour avec résumé des quadrants",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerUpcoming",
              label: "Eisenhower — Tâches à venir",
              minWidth: "180dp",
              minHeight: "110dp",
              targetCellWidth: 3,
              targetCellHeight: 2,
              description: "Toutes les tâches par ordre de priorité",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerBoard",
              label: "Eisenhower — Tableau de bord",
              minWidth: "250dp",
              minHeight: "200dp",
              targetCellWidth: 4,
              targetCellHeight: 3,
              description: "Calendrier et vue complète de toutes les tâches",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerMonthDefault",
              label: "Eisenhower — Calendrier mensuel",
              minWidth: "250dp",
              minHeight: "110dp",
              targetCellWidth: 4,
              targetCellHeight: 2,
              description: "Calendrier du mois avec points d'événements",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerMonthBloc",
              label: "Eisenhower — Calendrier Bloc",
              minWidth: "250dp",
              minHeight: "110dp",
              targetCellWidth: 4,
              targetCellHeight: 2,
              description: "Calendrier avec blocs colorés pour les jours avec événements",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerMonthClassique",
              label: "Eisenhower — Calendrier Classique",
              minWidth: "250dp",
              minHeight: "110dp",
              targetCellWidth: 4,
              targetCellHeight: 2,
              description: "Calendrier style classique épuré",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerSchedule",
              label: "Eisenhower — Emploi du temps",
              minWidth: "250dp",
              minHeight: "110dp",
              targetCellWidth: 4,
              targetCellHeight: 2,
              description: "Vos événements du jour",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
            {
              name: "EisenhowerFullCal",
              label: "Eisenhower — Calendrier complet",
              minWidth: "250dp",
              minHeight: "200dp",
              targetCellWidth: 4,
              targetCellHeight: 3,
              description: "Vue complète du mois avec événements",
              widgetFeatures: ["reconfigurable", "configuration_optional"],
            },
          ],
        },
      ],
      [
        "react-native-google-mobile-ads",
        {
          androidAppId: process.env.ADMOB_APP_ID_ANDROID || "ca-app-pub-3940256099942544~3347511713",
          iosAppId: process.env.ADMOB_APP_ID_IOS || "ca-app-pub-3940256099942544~3347511713",
        },
      ],
      [
        "expo-notifications",
        {
          color: "#EF4444",
        },
      ],
      [
        "expo-calendar",
        {
          calendarPermission: "L'app accède à votre calendrier pour afficher vos événements dans les widgets.",
        },
      ],
    ],
  },
};
